CREATE TABLE IF NOT EXISTS ORDERS 
(
ID INT NOT NULL IDENTITY, 
REFID INT NOT NULL, 
TYPE CHAR(1), 
STOCK VARCHAR(20), 
PRICE  DECIMAL(8,4),
QTY INT,
REM_QTY INT,
STATUS CHAR(1),
ENTRY_TIME DATETIME ,
LAST_UPDATE_TIME DATETIME
) ;

CREATE TABLE IF NOT EXISTS EXECUTIONS 
(
ID INT NOT NULL IDENTITY,
REFID INT NOT NULL,
STOCK VARCHAR(20), 
PRICE  DECIMAL(8,4),
QTY INT,
EXECUTION_TIME DATETIME,
LAST_UPDATE DATETIME
) ;

CREATE TABLE IF NOT EXISTS HOURLY_ANALYTICS
(
ID INT NOT NULL IDENTITY,
HOUR TIME NOT NULL,
STOCK VARCHAR(20),
TRADE_DATE DATE NOT NULL,
MIN_PRICE DECIMAL(8,4),
MAX_PRICE DECIMAL(8,4),
AVG_PRICE DECIMAL(8,4),
MIN_QTY INT,
MAX_QTY INT,
AVG_QTY INT,
MIN_VALUE DECIMAL(12,4),
MAX_VALUE DECIMAL(12,4),
AVG_VALUE DECIMAL(12,4),
ENTRY_TIME DATETIME,
LAST_UPDATE DATETIME
) ;


